// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVfl9Ljni4wihjoEcpt0VLoNKF7tzomFA',
    appId: '1:358405523640:web:1268bf227ec40864d10c4d',
    messagingSenderId: '358405523640',
    projectId: 'gogreenquetta-bdf69',
    authDomain: 'gogreenquetta-bdf69.firebaseapp.com',
    storageBucket: 'gogreenquetta-bdf69.firebasestorage.app',
    measurementId: 'G-X472JWQZF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4KztQ2MQIx7wUwTONp7BLlbVu3n8R7S0',
    appId: '1:358405523640:android:fd254d3e13c9a898d10c4d',
    messagingSenderId: '358405523640',
    projectId: 'gogreenquetta-bdf69',
    storageBucket: 'gogreenquetta-bdf69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdMGo4ZpOQCnon1DD961eWO3GEqLCKEVg',
    appId: '1:358405523640:ios:4829390d1edb6ae8d10c4d',
    messagingSenderId: '358405523640',
    projectId: 'gogreenquetta-bdf69',
    storageBucket: 'gogreenquetta-bdf69.firebasestorage.app',
    iosBundleId: 'com.example.gogreenquetta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdMGo4ZpOQCnon1DD961eWO3GEqLCKEVg',
    appId: '1:358405523640:ios:4829390d1edb6ae8d10c4d',
    messagingSenderId: '358405523640',
    projectId: 'gogreenquetta-bdf69',
    storageBucket: 'gogreenquetta-bdf69.firebasestorage.app',
    iosBundleId: 'com.example.gogreenquetta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVfl9Ljni4wihjoEcpt0VLoNKF7tzomFA',
    appId: '1:358405523640:web:87051bb9df181b7bd10c4d',
    messagingSenderId: '358405523640',
    projectId: 'gogreenquetta-bdf69',
    authDomain: 'gogreenquetta-bdf69.firebaseapp.com',
    storageBucket: 'gogreenquetta-bdf69.firebasestorage.app',
    measurementId: 'G-NWC8X5Y8CM',
  );
}
